In [1]:
from dotenv import load_dotenv
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#to move from notebooks/example_notebook.ipynb
import sys
import os
sys.path.append(os.path.abspath('../scripts'))

In [3]:
from load_data import load_data_using_sqlalchemy
from sql_queries import execute_telecom_queries

In [4]:
# Load environment variables from .env file
load_dotenv()

# Fetch database connection parameters from environment variables
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")

In [5]:
# Define the SQL query
query = "SELECT * FROM xdr_data;"

# Load data from PostgreSQL using SQLAlchemy
df = load_data_using_sqlalchemy(query)

# Display the first few rows of the dataframe
if df is not None:
    print("Successfully loaded the data")
else:
    print("Failed to load data.")

Successfully loaded the data

In [6]:
print("using the prefered method(SQLAlchemy)")
df

using the prefered method(SQLAlchemy)

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,1.585461e+07,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,2.024740e+07,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,1.972566e+07,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,2.138812e+07,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,1.525938e+07,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,None,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN

In [7]:
# Count missing values per column
missing_values = df.isnull().sum()

# Percentage of missing values per column
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

Bearer Id                                    0.660662
Start                                        0.000667
Start ms                                     0.000667
End                                          0.000667
End ms                                       0.000667
Dur. (ms)                                    0.000667
IMSI                                         0.379997
MSISDN/Number                                0.710662
IMEI                                         0.381331
Last Location Name                           0.768662
Avg RTT DL (ms)                             18.552543
Avg RTT UL (ms)                             18.541210
Avg Bearer TP DL (kbps)                      0.000667
Avg Bearer TP UL (kbps)                      0.000667
TCP DL Retrans. Vol (Bytes)                 58.763608
TCP UL Retrans. Vol (Bytes)                 64.432237
DL TP < 50 Kbps (%)                          0.502663
50 Kbps < DL TP < 250 Kbps (%)               0.502663
250 Kbps < DL TP < 1 Mbps (%)                0.502663
DL TP > 1 Mbps (%)                           0.502663
UL TP < 10 Kbps (%)                          0.527996
10 Kbps < UL TP < 50 Kbps (%)                0.527996
50 Kbps < UL TP < 300 Kbps (%)               0.527996
UL TP > 300 Kbps (%)                         0.527996
HTTP DL (Bytes)                             54.315638
HTTP UL (Bytes)                             54.539636
Activity Duration DL (ms)                    0.000667
Activity Duration UL (ms)                    0.000667
Dur. (ms).1                                  0.000667
Handset Manufacturer                         0.381331
Handset Type                                 0.381331
Nb of sec with 125000B < Vol DL             65.024900
Nb of sec with 1250B < Vol UL < 6250B       61.928920
Nb of sec with 31250B < Vol DL < 125000B    62.390251
Nb of sec with 37500B < Vol UL              86.835421
Nb of sec with 6250B < Vol DL < 31250B      58.877607
Nb of sec with 6250B < Vol UL < 37500B      74.561503
Nb of sec with Vol DL < 6250B                0.503330
Nb of sec with Vol UL < 1250B                0.528663
Social Media DL (Bytes)                      0.000000
Social Media UL (Bytes)                      0.000000
Google DL (Bytes)                            0.000000
Google UL (Bytes)                            0.000000
Email DL (Bytes)                             0.000000
Email UL (Bytes)                             0.000000
Youtube DL (Bytes)                           0.000000
Youtube UL (Bytes)                           0.000000
Netflix DL (Bytes)                           0.000000
Netflix UL (Bytes)                           0.000000
Gaming DL (Bytes)                            0.000000
Gaming UL (Bytes)                            0.000000
Other DL (Bytes)                             0.000000
Other UL (Bytes)                             0.000000
Total UL (Bytes)                             0.000667
Total DL (Bytes)                             0.000667
dtype: float64

In [8]:
#handling the missing value

import user_overview_EDA as uoe
uoe.handle_missing_values(df, unique_identifiers=['Bearer Id', 'IMSI', 'MSISDN/Number', 'IMEI'])

Checking column 'Bearer Id' for NaN values...
NaN values in 'Bearer Id': 991
Checking column 'IMSI' for NaN values...
NaN values in 'IMSI': 9
Checking column 'MSISDN/Number' for NaN values...
NaN values in 'MSISDN/Number': 495
Checking column 'IMEI' for NaN values...
NaN values in 'IMEI': 0

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,1.304243e+19,4/29/2019 7:28,615.0,4/30/2019 0:01,407.0,59587.0,2.082014e+14,3.366865e+10,3.533251e+13,T85721A,...,6550499.0,18003146.0,22468983.0,7149728.0,784435351.0,12724751.0,321383162.0,14890486.0,53745392.0,819016468.0
149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,16191667.0,11763428.0,17883703.0,19678161.0,526609673.0,9197207.0,3264510.0,13487416.0,57628851.0,574175259.0
149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,13877234.0,8288284.0,19350146.0,21293148.0,626893062.0,4735033.0,712180387.0,2457758.0,39135081.0,666648844.0
149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,22660510.0,1855903.0,9963942.0,5065760.0,553539484.0,13394316.0,121100856.0,11314729.0,34912224.0,592786405.0
149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8817106.0,8305402.0,3322253.0,13172589.0,352536971.0,2529475.0,814713113.0,1406930.0,29626096.0,371895920.0

In [9]:
#function to treat outliers
uoe.treat_outliers(df)

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,244958.75,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,244958.75,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,244958.75,2.082008e+14,3.373182e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,244958.75,2.082014e+14,3.373182e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,244958.75,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,1.304243e+19,4/29/2019 7:28,615.0,4/30/2019 0:01,407.0,59587.00,2.082014e+14,3.366865e+10,3.533251e+13,T85721A,...,6550499.0,18003146.0,22468983.0,7149728.0,784435351.0,12724751.0,321383162.0,14890486.0,53745392.0,819016468.0
149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.00,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,16191667.0,11763428.0,17883703.0,19678161.0,526609673.0,9197207.0,3264510.0,13487416.0,57628851.0,574175259.0
149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.00,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,13877234.0,8288284.0,19350146.0,21293148.0,626893062.0,4735033.0,712180387.0,2457758.0,39135081.0,666648844.0
149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.00,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,22660510.0,1855903.0,9963942.0,5065760.0,553539484.0,13394316.0,121100856.0,11314729.0,34912224.0,592786405.0
149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.00,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8817106.0,8305402.0,3322253.0,13172589.0,352536971.0,2529475.0,814713113.0,1406930.0,29626096.0,371895920.0

In [10]:
import Satisfaction_Analysis as sa
results = sa.full_analysis_pipeline(df, k=3)
print(results[['MSISDN/Number', 'Cluster', 'Engagement Score']])

       MSISDN/Number  Cluster  Engagement Score
0       3.360301e+10        1          0.272382
1       3.360301e+10        1          0.308107
2       3.360301e+10        1          0.306432
3       3.360301e+10        1          0.264121
4       3.360301e+10        1          0.248176
...              ...      ...               ...
89378   3.370000e+10        1          0.306432
89379   3.370000e+10        0          0.861052
89380   3.370000e+10        1          0.465907
89381   3.370000e+10        1          0.306432
89382   3.373182e+10        0          1.772933

[89383 rows x 3 columns]

In [11]:
#Displaying the top 10 satisfied customers

combined_metrics = sa.full_analysis_pipeline(df, k=3)
top_10_customers = sa.top_10_satisfied_customers(combined_metrics)
print("Top 10 Satisfied Customers:")
print(top_10_customers)

Top 10 Satisfied Customers:
       MSISDN/Number  Satisfaction Score
89382   3.373182e+10            1.843906
56379   3.366470e+10            1.700565
60161   3.366572e+10            1.700565
55995   3.366459e+10            1.700565
29612   3.365828e+10            1.700565
61105   3.366609e+10            1.694422
36189   3.365970e+10            1.677549
46379   3.366212e+10            1.669046
70357   3.366915e+10            1.662356
58158   3.366517e+10            1.661911

In [12]:
# predicting satisfaction score using regression model
sa.run_regression_on_combined_metrics(combined_metrics)

Mean Squared Error (MSE): 0.41350845370816575
R-squared (R2): -21.445599352032353

Predicted vs Actual Satisfaction Scores (Top 10):
         Actual  Predicted
76783  0.704661   0.751358
88572  0.674257   0.844048
47063  0.771110   0.927816
40206  1.252648   1.066064
59898  0.736164   0.725690
7492   0.619123   0.857332
56970  0.902694   0.875442
32189  0.867519   0.974769
12110  0.764233   0.626613
71426  0.775474   0.706577

In [13]:
# k-means (k=2) on the engagement & the experience score
combined_metrics_with_clusters = sa.run_kmeans_on_combined_metrics(combined_metrics)

# Displaying the result with clusters
print(combined_metrics_with_clusters[['MSISDN/Number', 'Engagement Score', 'Experience Score', 'KMeans Cluster']].head(10))

   MSISDN/Number  Engagement Score  Experience Score  KMeans Cluster
0   3.360301e+10          0.272382          0.948190               1
1   3.360301e+10          0.308107          0.967490               1
2   3.360301e+10          0.306432          1.194963               1
3   3.360301e+10          0.264121          1.296320               1
4   3.360301e+10          0.248176          1.294842               1
5   3.360301e+10          0.217478          1.292279               1
6   3.360302e+10          0.937055          1.275652               1
7   3.360302e+10          0.618851          1.148044               1
8   3.360302e+10          0.260551          1.300946               1
9   3.360302e+10          1.003158          1.019615               0

In [14]:
#Aggregate the average satisfaction & experience score per cluster
aggregated_scores = sa.aggregate_scores_per_cluster(combined_metrics_with_clusters)

# Display the aggregated scores per cluster
print(aggregated_scores)

   KMeans Cluster  Satisfaction Score  Experience Score
0               0            0.893978          0.678964
1               1            0.761508          1.196361

In [15]:
#function to create new table in the database
import load_data as ld 
ld.export_to_postgres(combined_metrics_with_clusters, 'user_metrics')

Table 'user_metrics' successfully created in the database.